#ifdef song__CARIBBEAN_DEF 
#include "song__CARIBBEAN.asm" 
#endif 
 
#ifdef song__HAWAIIAN_DEF 
#include "song__HAWAIIAN.asm" 
#endif 
 
#ifdef song__INDONESIAN_DEF 
#include "song__INDONESIAN.asm" 
#endif 
 
#ifdef song__LATIN_DEF 
#include "song__LATIN.asm" 
#endif 
 
#ifdef song__LATINFOLK_DEF 
#include "song__LATINFOLK.asm" 
#endif 
 
#ifdef song_AIAI_DEF 
#include "song_AIAI.asm" 
#endif 
 
#ifdef song_AKATONBO_DEF 
#include "song_AKATONBO.asm" 
#endif 
 
#ifdef song_ALOHAOE3_DEF 
#include "song_ALOHAOE3.asm" 
#endif 
 
#ifdef song_AMAZING_DEF 
#include "song_AMAZING.asm" 
#endif 
 
#ifdef song_AMEFURI_DEF 
#include "song_AMEFURI.asm" 
#endif 
 
#ifdef song_AMEKUMA_DEF 
#include "song_AMEKUMA.asm" 
#endif 
 
#ifdef song_AMETSUKI_DEF 
#include "song_AMETSUKI.asm" 
#endif 
 
#ifdef song_ANNI_DEF 
#include "song_ANNI.asm" 
#endif 
 
#ifdef song_ANPANMARCH_DEF 
#include "song_ANPANMARCH.asm" 
#endif 
 
#ifdef song_ANPANTAISO_DEF 
#include "song_ANPANTAISO.asm" 
#endif 
 
#ifdef song_AOIMENO_DEF 
#include "song_AOIMENO.asm" 
#endif 
 
#ifdef song_ARIA_DEF 
#include "song_ARIA.asm" 
#endif 
 
#ifdef song_AU_DEF 
#include "song_AU.asm" 
#endif 
 
#ifdef song_AWATENBOU_DEF 
#include "song_AWATENBOU.asm" 
#endif 
 
#ifdef song_AWATETOKOYA_DEF 
#include "song_AWATETOKOYA.asm" 
#endif 
 
#ifdef song_AWAY_DEF 
#include "song_AWAY.asm" 
#endif 
 
#ifdef song_BAMBA_DEF 
#include "song_BAMBA.asm" 
#endif 
 
#ifdef song_BANANABOAT_DEF 
#include "song_BANANABOAT.asm" 
#endif 
 
#ifdef song_BIRTHDAY_DEF 
#include "song_BIRTHDAY.asm" 
#endif 
 
#ifdef song_BIWAKO_DEF 
#include "song_BIWAKO.asm" 
#endif 
 
#ifdef song_BOLERO_DEF 
#include "song_BOLERO.asm" 
#endif 
 
#ifdef song_BRAHMS_DEF 
#include "song_BRAHMS.asm" 
#endif 
 
#ifdef song_BROWNJUG3_DEF 
#include "song_BROWNJUG3.asm" 
#endif 
 
#ifdef song_BUNBUNBUN_DEF 
#include "song_BUNBUNBUN.asm" 
#endif 
 
#ifdef song_CAMARADE_DEF 
#include "song_CAMARADE.asm" 
#endif 
 
#ifdef song_CHIGUSA_DEF 
#include "song_CHIGUSA.asm" 
#endif 
 
#ifdef song_CHOUCHOU_DEF 
#include "song_CHOUCHOU.asm" 
#endif 
 
#ifdef song_CHUURIPPU_DEF 
#include "song_CHUURIPPU.asm" 
#endif 
 
#ifdef song_CIELITOLINDO_DEF 
#include "song_CIELITOLINDO.asm" 
#endif 
 
#ifdef song_CLEMENTINE_DEF 
#include "song_CLEMENTINE.asm" 
#endif 
 
#ifdef song_COFFEERUMBA_DEF 
#include "song_COFFEERUMBA.asm" 
#endif 
 
#ifdef song_CONDOR_DEF 
#include "song_CONDOR.asm" 
#endif 
 
#ifdef song_DECKTHEHALL_DEF 
#include "song_DECKTHEHALL.asm" 
#endif 
 
#ifdef song_DENDEN_DEF 
#include "song_DENDEN.asm" 
#endif 
 
#ifdef song_DERRY_DEF 
#include "song_DERRY.asm" 
#endif 
 
#ifdef song_DONGURI_DEF 
#include "song_DONGURI.asm" 
#endif 
 
#ifdef song_DONGURI3_DEF 
#include "song_DONGURI3.asm" 
#endif 
 
#ifdef song_DOREMIFAAPM_DEF 
#include "song_DOREMIFAAPM.asm" 
#endif 
 
#ifdef song_DREAMER_DEF 
#include "song_DREAMER.asm" 
#endif 
 
#ifdef song_ELECTRICAL_DEF 
#include "song_ELECTRICAL.asm" 
#endif 
 
#ifdef song_FURUDOKEI_DEF 
#include "song_FURUDOKEI.asm" 
#endif 
 
#ifdef song_FURUSATO_DEF 
#include "song_FURUSATO.asm" 
#endif 
 
#ifdef song_FURUSATO4_DEF 
#include "song_FURUSATO4.asm" 
#endif 
 
#ifdef song_FUYUGESHIKI_DEF 
#include "song_FUYUGESHIKI.asm" 
#endif 
 
#ifdef song_FUYUNOUTA_DEF 
#include "song_FUYUNOUTA.asm" 
#endif 
 
#ifdef song_FUYUNOYORU_DEF 
#include "song_FUYUNOYORU.asm" 
#endif 
 
#ifdef song_GENKOTU_DEF 
#include "song_GENKOTU.asm" 
#endif 
 
#ifdef song_GOGATSUMURA_DEF 
#include "song_GOGATSUMURA.asm" 
#endif 
 
#ifdef song_GOLONDRINA_DEF 
#include "song_GOLONDRINA.asm" 
#endif 
 
#ifdef song_GONDOLA_DEF 
#include "song_GONDOLA.asm" 
#endif 
 
#ifdef song_HALELUYA_DEF 
#include "song_HALELUYA.asm" 
#endif 
 
#ifdef song_HAMABE_DEF 
#include "song_HAMABE.asm" 
#endif 
 
#ifdef song_HANA_DEF 
#include "song_HANA.asm" 
#endif 
 
#ifdef song_HARUKITA_DEF 
#include "song_HARUKITA.asm" 
#endif 
 
#ifdef song_HARUKOI_DEF 
#include "song_HARUKOI.asm" 
#endif 
 
#ifdef song_HARUOGAWA_DEF 
#include "song_HARUOGAWA.asm" 
#endif 
 
#ifdef song_HEIGH_HO_DEF 
#include "song_HEIGH_HO.asm" 
#endif 
 
#ifdef song_HINAMATSURI_DEF 
#include "song_HINAMATSURI.asm" 
#endif 
 
#ifdef song_HOLDIRIDIA_DEF 
#include "song_HOLDIRIDIA.asm" 
#endif 
 
#ifdef song_HOME_DEF 
#include "song_HOME.asm" 
#endif 
 
#ifdef song_HOSINEGAI_DEF 
#include "song_HOSINEGAI.asm" 
#endif 
 
#ifdef song_HOSISEKAI_DEF 
#include "song_HOSISEKAI.asm" 
#endif 
 
#ifdef song_HOTARUHIKARI3_DEF 
#include "song_HOTARUHIKARI3.asm" 
#endif 
 
#ifdef song_ICHIGATSU_DEF 
#include "song_ICHIGATSU.asm" 
#endif 
 
#ifdef song_IFUDODO_DEF 
#include "song_IFUDODO.asm" 
#endif 
 
#ifdef song_INUOMAWARI_DEF 
#include "song_INUOMAWARI.asm" 
#endif 
 
#ifdef song_ISSYUUKAN_DEF 
#include "song_ISSYUUKAN.asm" 
#endif 
 
#ifdef song_ITOMAKI_DEF 
#include "song_ITOMAKI.asm" 
#endif 
 
#ifdef song_JAMAICA_DEF 
#include "song_JAMAICA.asm" 
#endif 
 
#ifdef song_JINGLE_DEF 
#include "song_JINGLE.asm" 
#endif 
 
#ifdef song_JUPITER_DEF 
#include "song_JUPITER.asm" 
#endif 
 
#ifdef song_KAERUGASSHOU_DEF 
#include "song_KAERUGASSHOU.asm" 
#endif 
 
#ifdef song_KANASHIMINO_DEF 
#include "song_KANASHIMINO.asm" 
#endif 
 
#ifdef song_KANON_DEF 
#include "song_KANON.asm" 
#endif 
 
#ifdef song_KARATACHI_DEF 
#include "song_KARATACHI.asm" 
#endif 
 
#ifdef song_KARINKA_DEF 
#include "song_KARINKA.asm" 
#endif 
 
#ifdef song_KATYUSHA_DEF 
#include "song_KATYUSHA.asm" 
#endif 
 
#ifdef song_KAWAIANOKO_DEF 
#include "song_KAWAIANOKO.asm" 
#endif 
 
#ifdef song_KENTUCKY_DEF 
#include "song_KENTUCKY.asm" 
#endif 
 
#ifdef song_KIRAKIRABOSI_DEF 
#include "song_KIRAKIRABOSI.asm" 
#endif 
 
#ifdef song_KISYA_DEF 
#include "song_KISYA.asm" 
#endif 
 
#ifdef song_KISYAPOPO_DEF 
#include "song_KISYAPOPO.asm" 
#endif 
 
#ifdef song_KITTY_DEF 
#include "song_KITTY.asm" 
#endif 
 
#ifdef song_KODOMOTO_DEF 
#include "song_KODOMOTO.asm" 
#endif 
 
#ifdef song_KOHAN_DEF 
#include "song_KOHAN.asm" 
#endif 
 
#ifdef song_KOINOBORI3_DEF 
#include "song_KOINOBORI3.asm" 
#endif 
 
#ifdef song_KOKYONOSORA_DEF 
#include "song_KOKYONOSORA.asm" 
#endif 
 
#ifdef song_KUROIHITOMI_DEF 
#include "song_KUROIHITOMI.asm" 
#endif 
 
#ifdef song_KUTSUNARU_DEF 
#include "song_KUTSUNARU.asm" 
#endif 
 
#ifdef song_KYORO_DEF 
#include "song_KYORO.asm" 
#endif 
 
#ifdef song_MACHIBOUKE_DEF 
#include "song_MACHIBOUKE.asm" 
#endif 
 
#ifdef song_MAKIBAWA_DEF 
#include "song_MAKIBAWA.asm" 
#endif 
 
#ifdef song_MAMASOBA_DEF 
#include "song_MAMASOBA.asm" 
#endif 
 
#ifdef song_MATSUBARA_DEF 
#include "song_MATSUBARA.asm" 
#endif 
 
#ifdef song_MERIHITUJI_DEF 
#include "song_MERIHITUJI.asm" 
#endif 
 
#ifdef song_MICKY_DEF 
#include "song_MICKY.asm" 
#endif 
 
#ifdef song_MOMIJI_DEF 
#include "song_MOMIJI.asm" 
#endif 
 
#ifdef song_MOMOTARO_DEF 
#include "song_MOMOTARO.asm" 
#endif 
 
#ifdef song_MORIKUMA_DEF 
#include "song_MORIKUMA.asm" 
#endif 
 
#ifdef song_MUSIKOE_DEF 
#include "song_MUSIKOE.asm" 
#endif 
 
#ifdef song_MUSUNDE_DEF 
#include "song_MUSUNDE.asm" 
#endif 
 
#ifdef song_NANATSU_DEF 
#include "song_NANATSU.asm" 
#endif 
 
#ifdef song_NANATSU2_DEF 
#include "song_NANATSU2.asm" 
#endif 
 
#ifdef song_NATSUKINU_DEF 
#include "song_NATSUKINU.asm" 
#endif 
 
#ifdef song_NEKOHUN_DEF 
#include "song_NEKOHUN.asm" 
#endif 
 
#ifdef song_NEMURE_DEF 
#include "song_NEMURE.asm" 
#endif 
 
#ifdef song_NEMURE2_DEF 
#include "song_NEMURE2.asm" 
#endif 
 
#ifdef song_NOBARA_DEF 
#include "song_NOBARA.asm" 
#endif 
 
#ifdef song_OBENTOBAKO_DEF 
#include "song_OBENTOBAKO.asm" 
#endif 
 
#ifdef song_OBORO_DEF 
#include "song_OBORO.asm" 
#endif 
 
#ifdef song_ODOPON_DEF 
#include "song_ODOPON.asm" 
#endif 
 
#ifdef song_OKAASAN_DEF 
#include "song_OKAASAN.asm" 
#endif 
 
#ifdef song_ONCEINROYAL_DEF 
#include "song_ONCEINROYAL.asm" 
#endif 
 
#ifdef song_ONIPANTU_DEF 
#include "song_ONIPANTU.asm" 
#endif 
 
#ifdef song_ONMAHA_DEF 
#include "song_ONMAHA.asm" 
#endif 
 
#ifdef song_OOKINAKURI_DEF 
#include "song_OOKINAKURI.asm" 
#endif 
 
#ifdef song_OSHOGATSU_DEF 
#include "song_OSHOGATSU.asm" 
#endif 
 
#ifdef song_OSHOGATSU3_DEF 
#include "song_OSHOGATSU3.asm" 
#endif 
 
#ifdef song_OTUKAIARISAN_DEF 
#include "song_OTUKAIARISAN.asm" 
#endif 
 
#ifdef song_PECHKA_DEF 
#include "song_PECHKA.asm" 
#endif 
 
#ifdef song_PICNIC_DEF 
#include "song_PICNIC.asm" 
#endif 
 
#ifdef song_PONYO_DEF 
#include "song_PONYO.asm" 
#endif 
 
#ifdef song_RAILWAY_DEF 
#include "song_RAILWAY.asm" 
#endif 
 
#ifdef song_REPUBLIC_DEF 
#include "song_REPUBLIC.asm" 
#endif 
 
#ifdef song_ROMANCE_DEF 
#include "song_ROMANCE.asm" 
#endif 
 
#ifdef song_RYOSHU_DEF 
#include "song_RYOSHU.asm" 
#endif 
 
#ifdef song_SAINTS_DEF 
#include "song_SAINTS.asm" 
#endif 
 
#ifdef song_SAKURA2_DEF 
#include "song_SAKURA2.asm" 
#endif 
 
#ifdef song_SANPO_DEF 
#include "song_SANPO.asm" 
#endif 
 
#ifdef song_SANSAN_DEF 
#include "song_SANSAN.asm" 
#endif 
 
#ifdef song_SANTAMATI_DEF 
#include "song_SANTAMATI.asm" 
#endif 
 
#ifdef song_SAYAKANI_DEF 
#include "song_SAYAKANI.asm" 
#endif 
 
#ifdef song_SEIKURABE_DEF 
#include "song_SEIKURABE.asm" 
#endif 
 
#ifdef song_SENROWA_DEF 
#include "song_SENROWA.asm" 
#endif 
 
#ifdef song_SHOJOTANUKI_DEF 
#include "song_SHOJOTANUKI.asm" 
#endif 
 
#ifdef song_SIAWASENARA_DEF 
#include "song_SIAWASENARA.asm" 
#endif 
 
#ifdef song_SILENTNIGHT_DEF 
#include "song_SILENTNIGHT.asm" 
#endif 
 
#ifdef song_SILENTNIGHT3_DEF 
#include "song_SILENTNIGHT3.asm" 
#endif 
 
#ifdef song_SINJUGAI3_DEF 
#include "song_SINJUGAI3.asm" 
#endif 
 
#ifdef song_SINSEKAI4_DEF 
#include "song_SINSEKAI4.asm" 
#endif 
 
#ifdef song_SLEEVES_DEF 
#include "song_SLEEVES.asm" 
#endif 
 
#ifdef song_SMALLWORLD_DEF 
#include "song_SMALLWORLD.asm" 
#endif 
 
#ifdef song_SOUSYUNFU_DEF 
#include "song_SOUSYUNFU.asm" 
#endif 
 
#ifdef song_SYABONDAMA_DEF 
#include "song_SYABONDAMA.asm" 
#endif 
 
#ifdef song_TAKEDA_DEF 
#include "song_TAKEDA.asm" 
#endif 
 
#ifdef song_TAKIBI_DEF 
#include "song_TAKIBI.asm" 
#endif 
 
#ifdef song_TANABATA_DEF 
#include "song_TANABATA.asm" 
#endif 
 
#ifdef song_TEWOTATA_DEF 
#include "song_TEWOTATA.asm" 
#endif 
 
#ifdef song_THOMAS_DEF 
#include "song_THOMAS.asm" 
#endif 
 
#ifdef song_THOMAS2_DEF 
#include "song_THOMAS2.asm" 
#endif 
 
#ifdef song_TONTONHIGE_DEF 
#include "song_TONTONHIGE.asm" 
#endif 
 
#ifdef song_TOORIMICHI_DEF 
#include "song_TOORIMICHI.asm" 
#endif 
 
#ifdef song_TOTORO_DEF 
#include "song_TOTORO.asm" 
#endif 
 
#ifdef song_TRISTESSE_DEF 
#include "song_TRISTESSE.asm" 
#endif 
 
#ifdef song_TRISTESSE2_DEF 
#include "song_TRISTESSE2.asm" 
#endif 
 
#ifdef song_TROIKA_DEF 
#include "song_TROIKA.asm" 
#endif 
 
#ifdef song_UMI_DEF 
#include "song_UMI.asm" 
#endif 
 
#ifdef song_VRENELI_DEF 
#include "song_VRENELI.asm" 
#endif 
 
#ifdef song_WEWISH_DEF 
#include "song_WEWISH.asm" 
#endif 
 
#ifdef song_WINTERWONDER_DEF 
#include "song_WINTERWONDER.asm" 
#endif 
 
#ifdef song_YAMAONGAKUKA_DEF 
#include "song_YAMAONGAKUKA.asm" 
#endif 
 
#ifdef song_YOROKOBI4_DEF 
#include "song_YOROKOBI4.asm" 
#endif 
 
#ifdef song_YUKI_DEF 
#include "song_YUKI.asm" 
#endif 
 
#ifdef song_YURIKAGO_DEF 
#include "song_YURIKAGO.asm" 
#endif 
 
#ifdef song_YURIKAGO3_DEF 
#include "song_YURIKAGO3.asm" 
#endif 
 
#ifdef song_YUUKI100_DEF 
#include "song_YUUKI100.asm" 
#endif 
 
#ifdef song_YUUKIRINRIN_DEF 
#include "song_YUUKIRINRIN.asm" 
#endif 
 
#ifdef song_YUUYAKE_DEF 
#include "song_YUUYAKE.asm" 
#endif 
 
#ifdef song_ZOUSAN_DEF 
#include "song_ZOUSAN.asm" 
#endif 
 
